version: "3.8"

services:
  mc:
    image: itzg/minecraft-server/pupupupu
    environment:
      EULA: "false"
    ports:
      - "25565:25565"
    volumes:
      - data:/data
    stdin_open: false
    tty: true
    restart: unless-stopped
volumes:
  data: {}